app/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from werkzeug.security import generate_password_hash
from flask_login import UserMixin, current_user

db = SQLAlchemy()

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password = db.Column(db.String(256), nullable=False)
    post = db.relationship('Post', backref='author', lazy=True)

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = generate_password_hash(password)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False, unique=False)
    image = db.Column(db.String(20000))
    content = db.Column(db.String(300))
    date_created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __init__(self, title, image, content, user_id):
        self.title = title 
        self.image = image
        self.content = content
        self.user_id = user_id

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, EqualTo, Email

class UserInfoForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(),])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField()

app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from wtforms.widgets import TextArea
# Create a Posts Form. So users can create post and submit onto website. - MN
class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    image = StringField('Image URL', validators=[DataRequired(),])
    content = StringField("Content", validators=[DataRequired()], widget=TextArea())
    submit = SubmitField("Submit")

class UpdatePostForm(FlaskForm):
    title = StringField('Title')
    image = StringField('Image URL')
    content = StringField('Post Content')
    submit = SubmitField()

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


from .models import User, db

###### bring in routes for registration here #######
from .post.routes import post
from .auth.routes import auth




app = Flask(__name__)
app.config.from_object(Config)
migrate = Migrate(app,db)

from app import routes, models, post, auth

from .models import User, db

#### REGISTER BLUEPRINTS HERE


app.register_blueprint(auth)
app.register_blueprint(post)

login = LoginManager()

login.init_app(app)

## initialize db
db.init_app(app)

@login.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/post/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import current_user, login_required
from flask.helpers import flash
from werkzeug.datastructures import ContentRange

### IMPORT FORMS HERE ONCE WE HAVE THEM
from .forms import PostForm

from app.models import Post

# create instance of blueprint
post = Blueprint('post', __name__, template_folder='post_templates')

from app.models import db

@post.route('/feed')
def feedHome():
    posts = Post.query.all()
    return render_template('feed.html', posts = posts)


# Added Post Page route. - MN
@post.route('/create-post', methods=['GET', 'POST'])
@login_required
def add_post():
    posts = Post.query.all()
    form = PostForm()
    if form.validate_on_submit():
        # Clear the form after submitting. - MN
        title = form.title.data
        image = form.image.data
        content = form.content.data
        # Add post data to database. - MN
        post = Post(title, image, content, current_user.id)
        db.session.add(post)
        db.session.commit()
        # Return a message to user. - MN
        return redirect(url_for('post.feedHome'))
    return render_template('createpost.html', posts=posts, form=form)


@post.route('/posts/update/<int:id>', methods = ["GET","POST"])
@login_required
def updatePost(id):
    post = Post.query.filter_by(id=id).first()
    if post.user_id != current_user.id:
        return redirect(url_for('post.feedHome'))

@post.route('/posts/delete/<int:id>', methods = ["POST"])
@login_required
def deletePost(id):
    post = Post.query.filter_by(id=id).first()
    if post.user_id != current_user.id:
        return redirect(url_for('post.feedHome'))
    
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('post.feedHome'))

@post.route('/profile')
@login_required
def profile():
    posts = Post.query.filter_by(user_id=current_user.id)
    return render_template('profilepage.html', posts = posts)

app/routes.py
from flask import render_template, redirect, request, url_for, request, Blueprint
from werkzeug import datastructures
from app import app, db
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, login_required, current_user

from app.forms import UserInfoForm
from app.models import User

@app.route('/', methods=['GET','POST'] )
@app.route('/home')
def signMeUp():
    my_form = UserInfoForm()
    if request.method == "POST":
        if my_form.validate():
            
            username = my_form.username.data
            email = my_form.email.data
            password = my_form.password.data

            # create instance new user
            user = User(username, email, password)
            # add instance to databse
            db.session.add(user)
            # commit to databse
            db.session.commit()

            return render_template('feed.html')


        else:
            print('Not validated! :(')
    return render_template('home.html', form = my_form )

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/sidebar.css') }}">
<title>Title</title>
</head>
<body style="font-family: 'Raleway', sans serif; margin-top: 9vh;">

{% include 'nav.html' %}
    {% block content %}

    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="lbody">
	<div style="background-color: rgb(19, 18, 18); margin: 0;" class="row">
	  <div class="has-bg-img col-8">
		<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
			<ol class="carousel-indicators">
			  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
			  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
			  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner">
			  <div class="carousel-item active">
				<img style="height: 90vh;" class="d-block w-100" src="/static/img/dinner.jpg" alt="First slide">
				<div class="carousel-caption d-none d-md-block">
					<h3>Reconnect</h3>
					<p>Reminisce with your friends you may not have spoken<br> to in a while</p>
				  </div>
			  </div>
			  <div class="carousel-item">
				<img style="height: 90vh;" class="d-block w-100" src="/static/img/loop.png" alt="Second slide">
				<div class="carousel-caption d-none d-md-block">
					<h3>Stay In The Loop</h3>
					<p>Stay updated on current happenings around the globe!</p>
				  </div>
			  </div>
			  <div class="carousel-item">
				<img style="height: 90vh;" class="d-block w-100" src="/static/img/notifres.jpg" alt="Third slide">
				<div class="carousel-caption d-none d-md-block">
					<h3 style="color: black;">Be Heard</h3>
					<p style="color: black;">Keep your friends and loved ones updated on all things <br> happening with you!</p>
				  </div>
			  </div>
			</div>
			<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
			  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			  <span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
			  <span class="carousel-control-next-icon" aria-hidden="true"></span>
			  <span class="sr-only">Next</span>
			</a>
		  </div>
	  </div>
	  <div class="col">

<form action="" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset>
            {{ form.username.label }}
            {{ form.username(class='form-control', placeholder='Username') }}
        </fieldset>
        <fieldset>
            {{ form.email.label }}
            {{ form.email(class='form-control', placeholder='Email') }}
        </fieldset>
        <fieldset>
            {{ form.password.label }}
            {{ form.password(class='form-control', placeholder='Password') }}
        </fieldset>
        <fieldset>
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class='form-control', placeholder='Confirm Password') }}
        </fieldset>
        {{ form.submit(class='btn btn-primary') }}
		<a style="color: lightblue;" href="{{ url_for('auth.logMeIn') }}"> Already Have an Account? Sign in here.</a>
    </div>
	
    
</form>

		


        </div>


	  </div>
	</div>

</div>
{% endblock content %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color:#000000;">
  <div class="container-fluid">

    <!-- Navbar brand -->
    <a class="navbar-brand" href="#">Instabook</a>

    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mx-auto mb-lg-0">

        <!-- Link -->
        <li style="margin-right: 3vw;" class="nav-item">
          <a class="nav-link" href="{{ url_for('post.profile') }}">Your Profile</a>
        </li>
        <li  style="margin-right: 3vw;" class="nav-item">
            <a class="nav-link" href="{{ url_for('post.add_post') }}">Create a Post</a>
          </li>
          <li  style="margin-right: 3vw;" class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
      </ul>

      <!-- Icons -->
      <ul class="navbar-nav d-flex flex-row me-1">
        <li class="nav-item me-3 me-lg-0">
            <a class="nav-link" href="{{ url_for('post.feedHome') }}"><i class="bi bi-house-fill"></i></a>
          </li>
        <li class="nav-item me-3 me-lg-0">
            <a class="nav-link" href="#"><i class="bi bi-chat-dots"></i></a>
          </li>
        <li class="nav-item me-3 me-lg-0">
          <a class="nav-link" href="#"><i class="bi bi-bell"></i></a>
        </li>
        <li class="nav-item me-3 me-lg-0">
          <a class="nav-link" href="#"><i class="bi bi-bookmark-heart"></i></a>
        </li>
      </ul>

    </div>
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->